import sys
import os
import pandas as pd
import numpy as np

from audit_gm import NonHierachicalAuditGM, HierarchicalAuditGM


# Check which folder exists and append the correct path
base_path = os.path.abspath(os.path.join(os.path.dirname(__file__), '../'))
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), '../')))
if os.path.exists(os.path.join(base_path, 'Kalman')):
    from Kalman.kalman import MIN_OBS_FOR_EM, kalman_online_fit_predict_multicontext, likelihood_observation, contexts_to_probabilities
elif os.path.exists(os.path.join(base_path, 'KalmanFilterViz1D')):
    from KalmanFilterViz1D.kalman import MIN_OBS_FOR_EM, kalman_online_fit_predict_multicontext, likelihood_observation, contexts_to_probabilities
else:
    raise ImportError("Neither 'Kalman' nor 'KalmanFilterViz1D' folder found.")



if __name__ == "__main__":

    # Load generated sequences
    trials_path = '/home/clevyfidel/Documents/Workspace/Jasmin/experiment2alexclem/trial_lists/sub-test/sub-test_ses-1_trials.csv' # f'{trial_list_dir}sub-{participant}/sub-{participant}_ses-{session}_trials.csv'
    trials = pd.read_csv(trials_path)
    trials['dpos'] = trials['dpos'].fillna(0).astype(int)
    n_trials = len(trials)/8
    trials['relative_pos'] = np.tile(np.arange(8), int(n_trials)) # 1 to 8 for each run, to match dpos indexing
    trials['contexts'] = trials['relative_pos'] == trials['dpos'] # 0: standard, 1: deviant
    # dpos = 0 is actually not a deviant but an omission, so convert it to standard
    trials.loc[trials.dpos == 0, 'contexts'] = False

    # Prepare storage for predictions and likelihoods across runs
    all_per_ctx_mu_pred_std_at_dev = []
    all_per_ctx_sigma_pred_std_at_dev = []
    all_per_ctx_mu_pred_dev_at_dev = []
    all_per_ctx_sigma_pred_dev_at_dev = []
    all_likelihood_obs_std_at_dev = []
    all_likelihood_obs_dev_at_dev = []

    # Separate into runs
    for run_id in trials['run_n'].unique():
        run = trials[trials['run_n'] == run_id]

        # Get variables
        observations = run['observation']
        states_std = run['state_std']
        states_dev = run['state_dev']
        dpos = run['dpos']
        contexts = run['contexts']
        rules = run['rule']

        # Convert context labels to prior context probabilites for multicontext KF
        ctx_probabilities = contexts_to_probabilities(contexts, n_ctx=2) # shape (T, n_ctx)

        # Run multirule-multicontext KF
        # So far just run multi-context KF:
        mu_pred, sigma_pred, kfs_fitted, per_ctx_mu_pred, per_ctx_sigma_pred = kalman_online_fit_predict_multicontext(
            observations, ctx_probabilities, n_iter=5, return_per_ctx=True
        )

        # Note: 
        # - First MIN_OBS_FOR_EM + 1 predictions are np.nan
        # - So per_ctx_mu_pred[:MIN_OBS_FOR_EM + 1, 0] and per_ctx_mu_pred[:8*(MIN_OBS_FOR_EM)+(dpos[0]+1), 1] are np.nan
        

        # Evaluate per_ctx_mu_pred[ctx=std] at positions of deviant
        # per_ctx_mu_pred has dimensions (n_timesteps, n_ctx), so need to slice for timestep = when contexts is 1
        per_ctx_mu_pred_std_at_dev = per_ctx_mu_pred[contexts, 1] # should have len=sum(contexts==True)= #deviants in run
        per_ctx_sigma_pred_std_at_dev = per_ctx_sigma_pred[contexts, 1]
        per_ctx_mu_pred_dev_at_dev = per_ctx_mu_pred[contexts, 0] # should have len=sum(contexts==True)= #deviants in run
        per_ctx_sigma_pred_dev_at_dev = per_ctx_sigma_pred[contexts, 0]


        # Evaluate likelihood for observations at positions of deviant if they were generated by the predicted distribution for the standard context:
        observations_at_dev = observations[contexts]
        likelihood_obs_std_at_dev = likelihood_observation(
            y=observations_at_dev,
            mu=per_ctx_mu_pred_std_at_dev,
            sigma=per_ctx_sigma_pred_std_at_dev
        )

        likelihood_obs_dev_at_dev = likelihood_observation(
            y=observations_at_dev,
            mu=per_ctx_mu_pred_dev_at_dev,
            sigma=per_ctx_sigma_pred_dev_at_dev
        )

        # Study likelihood_obs_dev_at_dev - likelihood_obs_std_at_dev --> # TODO: plot

        
        # Compare likelihood_obs_std_at_dev against reaction times
        # TODO: load RTs
        

        # Store results for this run
        all_per_ctx_mu_pred_std_at_dev.append(per_ctx_mu_pred_std_at_dev)
        all_per_ctx_sigma_pred_std_at_dev.append(per_ctx_sigma_pred_std_at_dev)
        all_per_ctx_mu_pred_dev_at_dev.append(per_ctx_mu_pred_dev_at_dev)
        all_per_ctx_sigma_pred_dev_at_dev.append(per_ctx_sigma_pred_dev_at_dev)
        all_likelihood_obs_std_at_dev.append(likelihood_obs_std_at_dev)
        all_likelihood_obs_dev_at_dev.append(likelihood_obs_dev_at_dev)

    # After processing all runs, we can concatenate results across runs for further analysis
    all_per_ctx_mu_pred_std_at_dev = np.concatenate(all_per_ctx_mu_pred_std_at_dev)
    all_per_ctx_sigma_pred_std_at_dev = np.concatenate(all_per_ctx_sigma_pred_std_at_dev)
    all_per_ctx_mu_pred_dev_at_dev = np.concatenate(all_per_ctx_mu_pred_dev_at_dev)
    all_per_ctx_sigma_pred_dev_at_dev = np.concatenate(all_per_ctx_sigma_pred_dev_at_dev)
    all_likelihood_obs_std_at_dev = np.concatenate(all_likelihood_obs_std_at_dev)
    all_likelihood_obs_dev_at_dev = np.concatenate(all_likelihood_obs_dev_at_dev)

    # Save results to a CSV file for further analysis
    results_df = pd.DataFrame({
        'per_ctx_mu_pred_std_at_dev': all_per_ctx_mu_pred_std_at_dev,
        'per_ctx_sigma_pred_std_at_dev': all_per_ctx_sigma_pred_std_at_dev,
        'per_ctx_mu_pred_dev_at_dev': all_per_ctx_mu_pred_dev_at_dev,
        'per_ctx_sigma_pred_dev_at_dev': all_per_ctx_sigma_pred_dev_at_dev,
        'likelihood_obs_std_at_dev': all_likelihood_obs_std_at_dev,
        'likelihood_obs_dev_at_dev': all_likelihood_obs_dev_at_dev
    })
    results_df.to_csv('kalman_predictions_and_likelihoods_at_deviants.csv', index=False)

