

import pandas as pd
import numpy as np
import soundfile as sf
from datetime import date
import os

import sys
sys.path.append('/Users/steinj/Documents/2025_paradigm/thorns')

import thorns as th

#---- create logfile directory if not already existing
os.makedirs('logfiles_behavioral/', exist_ok=True)

session = '1-d2-si_stat0.1-si_r0.01_ses-01'
participant = '01'

if session == 'training':
    trial_list_dir = 'trial_lists_training/' # set directory for relevant trial list files (generated by generate_task_sequences.py)
else:
    trial_list_dir = 'trial_lists/'

#---- define variables to record
onset_sound = []
onset_tones = []

duration_sound = [] # based on theoretical duration
duration_sound_getsecs = [] # based on getsecs

offset_trial = [] # based on theroretical duretion

offset_sound = [] # based on theoretical duration
offset_sound_getsecs = [] # based on getsecs

onset_iti_list = [] # based on theoretical duration
onset_iti_list_getsecs = [] # based on getsecs

offset_iti_list = [] # based on theoretical duration
offset_iti_list_getsecs = [] # based on getsecs

ITI_list = [] # theoretical ITIs

tau = []

frequency = [] # tone frequency in Hz
lim_std = []
lim_dev = []

rule = [] # rule
dpos = [] # deviant positions
tone_type = [] # std or deviant

runs = []
trial_nr = []

#---- functions to generate soundwaves for the sounds and ISI/ITI
def generate_timbre_waveform(frequency = 1450.0, harmonics = [(1, 1.0), (2, 0.5), (3, 0.33), (4, 0.25), (5, 0.2)], duration = 0.1, sample_rate= 48000, ramp_time = 0.01, hanning = True):

    t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)
    waveform = np.zeros_like(t)

    for multiple, amplitude in harmonics:
        waveform += amplitude * np.sin(2 * np.pi * frequency * multiple * t)

    waveform /= np.max(np.abs(waveform))
    
    if hanning == False:
        ramp_samples = int(sample_rate * ramp_time)
        ramp = np.linspace(0, 1, ramp_samples)
        envelope = np.ones_like(waveform)
        envelope[:ramp_samples] *= ramp
        envelope[-ramp_samples:] *= ramp[::-1]
    
    elif hanning == True: 
        ramp_samples = int(sample_rate * ramp_time)
        full_window = np.hanning(2 * ramp_samples)
        ramp_in = full_window[:ramp_samples]
        ramp_out = full_window[ramp_samples:]

        envelope = np.ones_like(waveform)
        envelope[:ramp_samples] *= ramp_in
        envelope[-ramp_samples:] *= ramp_out

    return waveform * envelope * 0.3
    

def generate_isi(duration = 0.65, sample_rate = 48000):
    
    t = np.linspace(0, duration, int(sample_rate * duration), endpoint=False)
    waveform_isi = np.zeros_like(t)

    return waveform_isi

#---- define important variables

# possible implementation of different harmonics
harmonics_dict =  {
    "pure": [(1.0, 1.0)],
    "minor third": [(1, 1.0), (6/5, 0.5)], # 1/n
    "major third": [(1, 1.0), (5/4, 0.5)], # 1/n
    "perfect fourth": [(1, 1.0), (4/3, 0.5)], # 1/n
    "perfect fifth": [(1, 1.0), (3/2, 0.5)], # 1/n
    "minor sixth": [(1, 1.0), (8/5, 0.5)], # 1/n
    "major sixth": [(1, 1.0), (5/3, 0.5)], # 1/n
    "octave": [(1, 1.0), (2, 0.5)], # 1/n
    "1/n": [(n, 1/n) for n in range(1, 6)], # pure 1/n
    "1/n^2": [(n, 1/(n**2)) for n in range(1, 6)],
    "e^(-0.5(n-1))": [(n, np.exp(-0.5*(n - 1))) for n in range(1, 6)],
    "odd 1/n": [(n, 1/n) for n in range(1, 10, 2)]
}

harmonics = harmonics_dict['1/n'] # choose implementation of harmonics

sample_rate = 48000 # adjust to final device used!
ramp_time = 0.01 # ramp time for on/off ramps
stim_dur = 0.1 # total stmulus duration incl. on/off ramps
isi_dur = 0.65 # inter-stimulus-interval

response_window = 0.5 # --> too short? --> TODO pilot
trial_duration = (8*stim_dur) + (7*isi_dur) # trial duration
key_pos = ['v','y','u','i','l'] # response keys
key_pos_slider = ['1','2','3','4','5']
feedback_duration = 2 # feedback duration

#---- read in the pre-created trial lists
trials = pd.read_csv(f'{trial_list_dir}sub-{participant}/sub-{participant}_ses-{session}_trials.csv')
trials['dpos'] = trials['dpos'].fillna(0).astype(int)
n_trials = len(trials)/8

rts_getsecs_trial = [None]*int(n_trials) # RT based on ptb.getSecs() from onset trial
rts_getsecs_dev = [None]*int(n_trials) # RT based on ptb.getSecs() from onset deviant
rts_slider_getsecs = [None]*int(n_trials) # RT for confidence slider based on ptb.getSecs()
keys_pressed = [None]*int(n_trials) # pressed key
performance = [None]*int(n_trials) # correct?
confidence = [None]*int(n_trials) # confidence ratings

#---- more important variables
if session == 'training':
    run_step = len(trials)
    run_indices = [(i * run_step, (i + 1) * run_step) for i in range(1)]
    #print(run_indices)
else:
    run_step = len(trials) // 4
    run_indices = [(i * run_step, (i + 1) * run_step) for i in range(4)]
    #print(run_indices)

sound_list = []
len_waveform = []
buffer_handles = []


#---- load experiment: create all trials in advance from previously generated trial_list
for i in range(0, len(trials), 8):
    
    waveform = []
    oddball_trial = trials['frequency'][i:i + 8]
    
    dpos_trial = trials['dpos'][i:i+8]
    dposy = dpos_trial.iloc[0]
    dposy = int(dposy)
    dpos.append(dposy)
    
    run_trial = trials['run_n'][i:i+8]
    runy = run_trial.iloc[0]
    runs.append(runy)
    
    rule_trial = trials['rule'][i:i+8]
    ruly = rule_trial.iloc[0]
    rule.append(ruly)
    
    tones_trial = np.zeros(8)
    if dposy != 0:
        tones_trial[dposy] = 1
    tone_type.append(tones_trial.astype(int))
    
    trial_trial = trials['trial_n'][i:i+8]
    trialy = trial_trial.iloc[0]
    trial_nr.append(trialy)
    
    tau_std_trial = trials['tau_std'][i:i+8]
    tauy = tau_std_trial.iloc[0]
    tau.append(tauy)
    
    lim_std_trial = trials['lim_std'][i:i+8]
    lim_stdy = lim_std_trial.iloc[0]
    lim_std.append(lim_stdy)
    
    lim_dev_trial = trials['lim_dev'][i:i+8]
    lim_devy = lim_dev_trial.iloc[0]
    lim_dev.append(lim_devy)
            
    ITI = trials['ITI'][i]
    ITI_list.append(ITI)

# insert catch trials
catch_all = []
n_catch = 10
catch_pos = [[]]*len(np.unique(runs))

for runn in np.unique(runs):

    done = False

    positions = np.where(
    (np.array(runs) == runn) &
    (np.isin(np.array(rule), [0, 1]))
    )
    
    positions_5 = positions[0][np.where((np.array(dpos)[positions[0]] == 6))[0]]
    positions_not_5 = positions[0][np.where((np.array(dpos)[positions[0]] != 6))[0]]

    while done == False:
        catch_pos[runn] = []
        
        # get five positions with dev = 5 and five with dev != 5
        while len(catch_pos[runn]) < n_catch/2:
            test_pos = np.random.choice(positions_5)
            catch_pos[runn].append(test_pos)
        while len(catch_pos[runn]) < n_catch:
            test_pos = np.random.choice(positions_not_5)
            catch_pos[runn].append(test_pos)

        catch_pos[runn] = sorted(catch_pos[runn])
        print(catch_pos[runn])

        done = (
        all(catch_pos[runn][i] - catch_pos[runn][i-1] > 2 for i in range(1, len(catch_pos[runn]))) # at least two trials in between
        and not np.isin(catch_pos[runn], [np.where(runs == runn)[0][0], np.where(runs == runn)[0][-1]]).any() # not first or last trial
        )

    data_run = np.array([runs == runn])
    catch_pos_run = np.zeros(len(np.where(data_run[0]==True)[0]))
    catch_pos[runn] = list(map(lambda x: x + 1, catch_pos[runn]))
    catch_pos_run[catch_pos[runn]-np.where(runs == runn)[0][0]] = 1

    catch_all.append(catch_pos_run)

catch_all = [item for sublist in catch_all for item in sublist] 
print(catch_all)
catch_key_list = []
catch_correct_list = []
catch_rt_list = []
is_catch = []